sudo: required
services:
  - docker
languages: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t pellegrino/gocd-server-arm .
